name: ridge_fin
description: "A stock watchlist app created by Fidel Hen"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  auto_route: ^11.1.0
  get_it: ^9.2.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  dio: ^5.9.0
  injectable: ^2.7.1+4
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^6.0.0
  skeletonizer: ^2.1.2
  flutter_animate: ^4.5.2
  shared_preferences: ^2.5.4
  google_fonts: ^7.0.0
  supabase_flutter: ^2.12.0
  equatable: ^2.0.8
  flutter_form_builder: ^10.2.0
  fl_chart: ^1.1.1
  intl: ^0.20.2
  url_launcher: ^6.3.1
  animated_flip_counter: ^0.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.10.4
  auto_route_generator: ^10.4.0
  json_serializable: ^6.11.3
  freezed: ^3.2.4

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
